[package]
name = "mt_tqdm"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
pyo3 = { version = "0.22.2", features = ["extension-module"] }
rayon = "1.10.0"
libc = "0.2"
num_cpus = "1.16.0"

[lib]
crate-type = ["cdylib"]
name = "mt_tqdm"